### ISSUE TITLE
Code pipeline failing in BuildImage Stage

### ISSUE THREAD

**Issue by Deepak-Kumar-AS** [aws-samples/immutable-server-pipeline#4]
While deploying the code in AWS, its failing while creating BuildImage stack stage. 
**Action details**
Stage name : BuildImage
Action name: apply_change_set
Namespace: BuildImgCFParamApplyVars

**Action configuration**
ActionMode: CHANGE_SET_EXECUTE
ChangeSetName: buildimage
StackName: Demo1-BuildImg

Action execution failed
Failed to execute change set. Current stack status: ROLLBACK_COMPLETE. Reason: No reason was provided.

**Comment by Deepak-Kumar-AS** [comment]
@adriaandejonge Please let me know if you need more information on above reported bug.

**Comment by adriaandejonge** [comment]
Thanks for reporting, @Deepak-Kumar-AS Let me try to reproduce this and troubleshoot.

**Comment by adriaandejonge** [comment]
Looks like a permission issue:

```
User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/ImmutableServerTestPipeline-BuildImgCFRole-VFQRFCHL7G8C/AWSCloudFormation is not authorized to perform: imagebuilder:GetImage on resource: arn:aws:imagebuilder:us-east-1:YYYYYYYYYYYY:image/amazon-linux-2-x86/2021.3.4/1 (Service: Imagebuilder, Status Code: 403, Request ID: (removed), Extended Request ID: null)
```
The CloudFormation template assumes all images come from the same source account ID. I'll propose an update for this.

**Comment by adriaandejonge** [comment]
Thanks again, @Deepak-Kumar-AS - much appreciated!
